# Generated by Django 3.2.4 on 2022-10-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('conversationId', models.CharField(max_length=500)),
                ('payload', models.CharField(max_length=500)),
                ('botResponse', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
